# Move base node parameters. For full documentation of the parameters in this file, please see
#
#  http://www.ros.org/wiki/move_base
#
#base_local_planner: base_local_planner/TrajectoryPlannerROS
base_local_planner: dwa_local_planner/DWAPlannerROS

shutdown_costmaps: false

controller_frequency: 4.0
controller_patience: 5.0

planner_frequency: 0.5
planner_patience: 2.1
planner_overclock_ratio: 1
#planner thread is checked planner_overclock_ratio * planner_frequency - to handle new goals 

oscillation_timeout: 15.0
oscillation_distance: 0.2


